name: "YAGA Plugin"

on:
  release:
    types: [created]
    
jobs:
  plugin:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1.13.0
        with:
          arch: x86
 
      - name: Compile plugin
        run: msbuild /p:Configuration="MP x2 MT Release"

      - name: Upload plugin
        uses: actions/upload-artifact@v4
        with:
          name: yaga-dll
          path: "Bin/YAGA.dll"
          compression-level: 0
          overwrite: true