name: "YAGA CI/CD"

on:
  release:
    types: [created]
    
jobs:
  yaga:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: true

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1.13.0
        with:
          arch: x86
 
      - name: Compile yaga.dll
        run: msbuild /p:Configuration="MP x2 MT Release"

      - name: Build yaga.vdf
        run: ./vdfsbuilder.exe build.vm
        working-directory: ./VDF

      - name: Upload yaga.vdf
        uses: softprops/action-gh-release@v2
        with:
          files: "VDF/yaga.vdf"