name: "YAGA VDF"

on:
  workflow_run:
    workflows: [YAGA Plugin]
    types: [completed]
    
jobs:
  vdf:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download plugin
        uses: actions/download-artifact@v4
        with:
          #name: yaga-dll
          path: VDF/System/Autorun
          github-token: ${{ secrets.GH_PAT }}
          repository: nuno69/yaga
          run-id: ${{ github.event.workflow_run.id }}

      - name: Build VDF
        run: ./vdfsbuilder.exe build.vm
        working-directory: ./VDF

      - name: Upload yaga.vdf
        uses: softprops/action-gh-release@v2
        with:
          files: "Bin/YAGA.vdf"