name: "YAGA VDF"

on:
  workflow_run:
    workflows: [YAGA Plugin]
    types: [completed]
    
jobs:
  vdf:
    runs-on: windows-latest

    steps:
      - name: Download plugin
        uses: actions/download-artifact@v4
        with:
          name: yaga-dll
          path: "VDF/System/Autorun/yaga.dll"

      - name: Build VDF
        run: vdfsbuilder.exe build.vm
        working-directory: ./VDF

      - name: Upload yaga.vdf
        uses: softprops/action-gh-release@v2
        with:
          files: "Bin/YAGA.vdf"